project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.qmd"

website:
  title: "aman9das"
  favicon: "_assets/avatar/avatar-gradient-round.webp"
  description: "Aman Das' Personal Website"
  site-url: https://aman9das.github.io/
  navbar:
    right:
      - text: Blog
        href: blog/index.qmd
  page-footer:
    left:
      - text: Built with Quarto
        href: https://quarto.org
    right:
      - icon: rss
        href: blog/index.xml
      - icon: github
        href: https://github.com/Aman9das/
      - icon: mastodon
        href: https://fosstodon.org/@Aman9das
    
format:
  html:
    theme:
      dark:
        - cosmo
        - _assets/theme/dark.scss
      light:
        - cosmo
        - _assets/theme/light.scss
    highlight-style: a11y

execute:
  freeze: auto

editor: visual

