project:
  type: website

website:
  title: "Aman Das"
  description: "This is Aman Das' personal blog."
  site-url: https://aman9das.github.io/
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
      - icon: github
        href: https://github.com/Aman9das/
      - icon: mastodon
        href: https://fosstodon.org/@Aman9das
format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    css: styles.css

execute:
  freeze: auto

editor: visual

