project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "blog/**/*.*md"
    - "colophon/*.*md"

website:
  title: "aman9das"
  favicon: "_assets/avatar/avatar-gradient-round.webp"
  description: "Aman Das' Personal Website"
  site-url: https://aman9das.github.io/
  repo-url: https://github.com/Aman9das/Aman9das.github.io
  repo-actions:
    - source
    - issue
  twitter-card: true
  navbar:
    right:
      - text: Blog
        href: blog/
  page-footer:
    left:
      - text: Made with 🩵
        href: colophon/
    right:
      - icon: rss
        href: blog/index.xml
    
format:
  html:
    theme:
      dark:
        - _assets/theme/dark.scss
      light:
        - _assets/theme/light.scss
    highlight-style: a11y

execute:
  freeze: auto
