project:
  type: website

website:
  title: "Aman Das"
  description: "This is Aman Das' personal blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/Aman9das/
      - icon: mastodon
        href: https://fosstodon.org/@Aman9das
format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    css: styles.css

editor: visual

